github: [EndiHariadi43]
custom: ["https://github.com/sponsors/EndiHariadi43", "https://saweria.co/EndiHariadi43"]
```yml
github: [EndiHariadi43]
custom: ["https://github.com/sponsors/EndiHariadi43", "https://gumroad.com/your-product", "https://saweria.co/EndiHariadi43"]
