name: Laravel CI (Lite)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      # Hanya cache composer kalau ada composer.json
      - name: Cache Composer
        if: hashFiles('**/composer.json') != ''
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      # Hanya install dependencies kalau ada composer.json
      - name: Install Dependencies (prod-like)
        if: hashFiles('**/composer.json') != ''
        run: composer install --no-interaction --prefer-dist --no-progress --no-dev --optimize-autoloader

      # Langkah khusus Laravel — hanya jalan kalau ada artisan
      - name: Generate app key (if Laravel)
        if: hashFiles('**/artisan') != ''
        run: |
          php -r "if(!file_exists('.env') && file_exists('.env.example')) copy('.env.example','.env');"
          php artisan key:generate --no-interaction || true

      # Jalankan test hanya bila ada composer.json (project PHP/Laravel)
      - name: Run Tests (if available)
        if: hashFiles('**/composer.json') != ''
        run: |
          if [ -f artisan ]; then
            php artisan test --no-interaction || true
          elif [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --colors=always || true
          else
            echo "No test runner found, skipping."
          fi

      # Build frontend hanya jika ada package.json
      - name: Build Frontend (optional)
        if: hashFiles('**/package.json') != ''
        run: |
          (npm ci || pnpm i || yarn) || true
          (npm run build || pnpm build || yarn build) || true

      # Upload artifact tapi abaikan jika tidak ada file
      - name: Artifacts (ignore if missing)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            vendor
            public/build
            bootstrap/cache
          if-no-files-found: ignore

      - name: 💎 Upgrade to Premium for Deploy + Alerts
        run: |
          echo "This is the LITE edition."
          echo "Premium adds: SSH/Rsync/Deployer, zero-downtime, .env templating, Telegram/Slack alerts, rollbacks, multi-env."
          echo "➡ https://github.com/sponsors/EndiHariadi43"
